theme: jekyll-theme-cayman
title: e.Tin, the first electronic swear tin
description: You wish to work in a more quiet and peaceful place where swearing out loud is a faraway memory? eTin will help you turn those nasty habits on occasion to contribute to actions you care about !
show_downloads: true