server:
    port: 80
    servlet:
        context-path: /
        jsp:
            registered: false
    error:
        whitelabel: 
            enabled: false

spring:
    application:
        name: etin
    banner:
        location: classpath:banners/banner-prod.txt
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://localhost:3306/etin?createDatabaseIfNotExist=false&useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
        username: staff
        password:
    jpa:
        open-in-view: false
        show-sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: false
                jdbc:
                    batch_size: 10
                    order_inserts: false
                    order_updates: false
                    generate_statistics: false
    messages:
        use-code-as-default-message: false
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false

logging:
    config: classpath:logback/logback-spring.xml

jwt-auth-server:
    keyStore: swear-tin.jks
    keyAlias: SwearTinKey
    keyPass: Rz67nH496643GnY236dRmOkb67
    accessTokenValiditySeconds: 1800
    refreshTokenValiditySeconds: 86400