name: Node CI

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run:
        npm install --prefix application/web-ui
        npm ci --prefix application/web-ui
        npm run build --if-present --prefix application/web-ui
        npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --prefix application/web-ui
        npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js --prefix application/web-ui
      env:
        CI: true
